name: src
description: A sample command-line application with basic argument parsing.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.0-edge.42ccd79cd12a640359fb729537f5b14a06055188

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  google_generative_ai: ^0.2.2
  logger: ^2.1.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
